projects:
  faketwitterbackend:
    schemaPath: src/graphql/schema.json
    includes:
      - /items
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /
